### ISSUE TITLE
line 1803     headers_useragents.append('Mozilla/5.0 (Windows; U; Windows NT 6.1; en; rv:1.9.1.3) Gecko/20090824 Firefox/3.5.3 (.NET CLR 3.5.30729)') TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by kathith-404** [IkzCx/ProgramsForDDos#5]
https://github.com/IkzCx/ProgramsForDDos/blob/6242138f4a1fbbcb24c329f47282e7a73fc3864c/Saphyra.py#L1803

**Comment by kathith-404** [comment]
line 1803
    headers_useragents.append('Mozilla/5.0 (Windows; U; Windows NT 6.1; en; rv:1.9.1.3) Gecko/20090824 Firefox/3.5.3 (.NET CLR 3.5.30729)')
TabError: inconsistent use of tabs and spaces in indentation

**Comment by alphaneru** [comment]
Use python 2
